export const assets = [
  "/assets/about1.jpg",
  "/assets/about2.jpg",
  "/assets/Arbo.PNG",
  "/assets/Aria.PNG",
  "/assets/Ariala.PNG",
  "/assets/back.PNG",
  "/assets/battle.gif",
  "/assets/battleloop.mp3",
  "/assets/battleloop2.mp3",
  "/assets/battlemusic.mp3",
  "/assets/battlemusic2.mp3",
  "/assets/Blastoise.PNG",
  "/assets/bulbasaur.gif",
  "/assets/Bulbasaur.PNG",
  "/assets/Butterfree.PNG",
  "/assets/Caterpie.PNG",
  "/assets/charmander.gif",
  "/assets/Charmander.PNG",
  "/assets/classic.gif",
  "/assets/coin.mp3",
  "/assets/coinlost.mp3",
  "/assets/coinwon.mp3",
  "/assets/cover.png",
  "/assets/Dragonite.PNG",
  "/assets/explosion.mp3",
  "/assets/favicon.ico",
  "/assets/Flareon.PNG",
  "/assets/flip.gif",
  "/assets/gameboyfont.ttf",
  "/assets/Geodude.PNG",
  "/assets/Grimer.PNG",
  "/assets/Haunter.PNG",
  "/assets/head.png",
  "/assets/hit.mp3",
  "/assets/Ivysaur.PNG",
  "/assets/Jigglypuff.PNG",
  "/assets/Kang.PNG",
  "/assets/Karate.PNG",
  "/assets/lose.mp3",
  "/assets/losecheck.png",
  "/assets/main_menu.mp3",
  "/assets/match.mp3",
  "/assets/Meowth.PNG",
  "/assets/metal.mp3",
  "/assets/misteryback.png",
  "/assets/misteryfront.png",
  "/assets/muted.png",
  "/assets/mutedb.png",
  "/assets/Neptune.PNG",
  "/assets/next.png",
  "/assets/nextb.png",
  "/assets/Nidoran.PNG",
  "/assets/Nidorina.PNG",
  "/assets/OP_UI.png",
  "/assets/Orphon.png",
  "/assets/pause.png",
  "/assets/pauseb.png",
  "/assets/Persian.PNG",
  "/assets/Pidgotto.PNG",
  "/assets/pikachu.mp3",
  "/assets/Pikachu.PNG",
  "/assets/pikachuyellow.gif",
  "/assets/pikapika.gif",
  "/assets/pikapika.mp3",
  "/assets/pkmn.png",
  "/assets/play.png",
  "/assets/playb.png",
  "/assets/PL_UI.png",
  "/assets/pokeball.mp3",
  "/assets/pokegang.gif",
  "/assets/prev.png",
  "/assets/prevb.png",
  "/assets/Psyduck.PNG",
  "/assets/Raichu.PNG",
  "/assets/Raticate.PNG",
  "/assets/Rattata.PNG",
  "/assets/runaway.mp3",
  "/assets/runaway.png",
  "/assets/Sandshrew.png",
  "/assets/select.mp3",
  "/assets/sfx_attacks/Acid Armor.mp3",
  "/assets/sfx_attacks/Agility.mp3",
  "/assets/sfx_attacks/Amnesia.mp3",
  "/assets/sfx_attacks/Aurora Beam.mp3",
  "/assets/sfx_attacks/Bite.mp3",
  "/assets/sfx_attacks/Blizzard.mp3",
  "/assets/sfx_attacks/Body Slam.mp3",
  "/assets/sfx_attacks/Bone Club.mp3",
  "/assets/sfx_attacks/Bonemerang.mp3",
  "/assets/sfx_attacks/Bug Bite.mp3",
  "/assets/sfx_attacks/Comet Punch.mp3",
  "/assets/sfx_attacks/Confused.mp3",
  "/assets/sfx_attacks/Confusion.mp3",
  "/assets/sfx_attacks/Dazzling Gleam.mp3",
  "/assets/sfx_attacks/Dizzy Punch.mp3",
  "/assets/sfx_attacks/Double Kick.mp3",
  "/assets/sfx_attacks/Double Slap.mp3",
  "/assets/sfx_attacks/Double-Edge.mp3",
  "/assets/sfx_attacks/Dragon Dance.mp3",
  "/assets/sfx_attacks/Dragon Rage.mp3",
  "/assets/sfx_attacks/Dream Eater.mp3",
  "/assets/sfx_attacks/Ember.mp3",
  "/assets/sfx_attacks/Feather Dance.mp3",
  "/assets/sfx_attacks/Feint Attack.mp3",
  "/assets/sfx_attacks/Flamethrower.mp3",
  "/assets/sfx_attacks/Focus Energy.mp3",
  "/assets/sfx_attacks/Fury Swipes.mp3",
  "/assets/sfx_attacks/Glare.mp3",
  "/assets/sfx_attacks/Growl.mp3",
  "/assets/sfx_attacks/Gust.mp3",
  "/assets/sfx_attacks/Harden.mp3",
  "/assets/sfx_attacks/Headbutt.mp3",
  "/assets/sfx_attacks/Horn Attack.mp3",
  "/assets/sfx_attacks/Hurricane.mp3",
  "/assets/sfx_attacks/Hydro Pump.mp3",
  "/assets/sfx_attacks/Hyper Fang.mp3",
  "/assets/sfx_attacks/Hyper Voice.mp3",
  "/assets/sfx_attacks/Hypnosis.mp3",
  "/assets/sfx_attacks/Karate Chop.mp3",
  "/assets/sfx_attacks/Leer.mp3",
  "/assets/sfx_attacks/Lick.mp3",
  "/assets/sfx_attacks/Low Kick.mp3",
  "/assets/sfx_attacks/Magnitude.mp3",
  "/assets/sfx_attacks/Mega Punch.mp3",
  "/assets/sfx_attacks/Meteor Mash.mp3",
  "/assets/sfx_attacks/Minimize.mp3",
  "/assets/sfx_attacks/Moonblast.mp3",
  "/assets/sfx_attacks/Pay Day.mp3",
  "/assets/sfx_attacks/Poison Sting.mp3",
  "/assets/sfx_attacks/Poison Tail.mp3",
  "/assets/sfx_attacks/Pound.mp3",
  "/assets/sfx_attacks/Psybeam.mp3",
  "/assets/sfx_attacks/Psychic.mp3",
  "/assets/sfx_attacks/Quick Attack.mp3",
  "/assets/sfx_attacks/Rapid Spin.mp3",
  "/assets/sfx_attacks/Razor Leaf.mp3",
  "/assets/sfx_attacks/Recover.mp3",
  "/assets/sfx_attacks/Rock Slide.mp3",
  "/assets/sfx_attacks/Rock Throw.mp3",
  "/assets/sfx_attacks/Sand Attack.mp3",
  "/assets/sfx_attacks/Scratch.mp3",
  "/assets/sfx_attacks/Screech.mp3",
  "/assets/sfx_attacks/Seismic Toss.mp3",
  "/assets/sfx_attacks/Shadow Ball.mp3",
  "/assets/sfx_attacks/Sing.mp3",
  "/assets/sfx_attacks/Slap.mp3",
  "/assets/sfx_attacks/Slash.mp3",
  "/assets/sfx_attacks/Sleep Powder.mp3",
  "/assets/sfx_attacks/Sludge.mp3",
  "/assets/sfx_attacks/Spark.mp3",
  "/assets/sfx_attacks/String Shot.mp3",
  "/assets/sfx_attacks/Supersonic.mp3",
  "/assets/sfx_attacks/Surf.mp3",
  "/assets/sfx_attacks/Swift.mp3",
  "/assets/sfx_attacks/Tackle.mp3",
  "/assets/sfx_attacks/Take Down.mp3",
  "/assets/sfx_attacks/Thunder Punch.mp3",
  "/assets/sfx_attacks/Thunder Wave.mp3",
  "/assets/sfx_attacks/Thunder.mp3",
  "/assets/sfx_attacks/Thunderbolt.mp3",
  "/assets/sfx_attacks/Vine Whip.mp3",
  "/assets/sfx_attacks/Water Gun.mp3",
  "/assets/sfx_attacks/Water Pulse.mp3",
  "/assets/sfx_attacks/Waterfall.mp3",
  "/assets/sfx_attacks/Wing Attack.mp3",
  "/assets/sfx_attacks/Withdraw.mp3",
  "/assets/Slowbro.PNG",
  "/assets/Slowmo.PNG",
  "/assets/squirtle.gif",
  "/assets/Squirtle.PNG",
  "/assets/squirtle2.gif",
  "/assets/start.mp3",
  "/assets/start2.mp3",
  "/assets/Staryu.PNG",
  "/assets/supereffective.mp3",
  "/assets/supereffective_prev.mp3",
  "/assets/tails.png",
  "/assets/themes.png",
  "/assets/themesb.png",
  "/assets/tie.mp3",
  "/assets/Voltorb.PNG",
  "/assets/volume.png",
  "/assets/volumeb.png",
  "/assets/Wigglytuff.PNG",
  "/assets/wincheck.png",
  "/assets/youlose.mp3",
  "/assets/youwin.mp3"
];
